# Generated by Django 5.0.6 on 2024-06-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='purchase_quantity',
        ),
    ]
