# Generated by Django 5.0.6 on 2024-06-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.address'),
        ),
    ]
