# Generated by Django 5.0.6 on 2024-06-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_customer_address_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
    ]
